function TaskTrackCore(c){var e=this,l=$.Deferred();this.dbInit=new DB_Adapter({name:"TaskTrack DB"});this.dbInit.done(function(c){e.dbAdapter=c;e.initialize(l)}).fail(function(){throw Error("Cannot connect to inDB!");}).progress(function(){Utils.log("Waiting for inDB...")});return l.promise()}var TT_PROJECTS=[1,"projectList"],TT_TASKS=[2,"taskList"],TASK_PAUSED=0,TASK_ACTIVE=1,E_INV_SYNC_METHOD=100,E_MISS_DATA=101,E_MISS_LOGIN_PASS=102,E_INV_LOGIN_PASS=103,E_FAIL_SAVE_DATA=104;
TaskTrackCore.prototype.version="1.0.0";TaskTrackCore.prototype.dbAdapter;TaskTrackCore.prototype.db;TaskTrackCore.prototype.projectList=[];TaskTrackCore.prototype.taskList=[];TaskTrackCore.prototype.synced=!1;TaskTrackCore.prototype.up2date=!0;TaskTrackCore.prototype.isConnected=!1;TaskTrackCore.prototype.sharedDfd=null;TaskTrackCore.prototype.sharedDfd2=null;TaskTrackCore.prototype.dfdFlag=0;
TaskTrackCore.prototype.initialize=function(c){var e=this;this.db=this.dbAdapter.db;this.initSettings();$.when(this.clearTableListCache(TT_PROJECTS,!0),this.clearTableListCache(TT_TASKS,!0)).done(function(){c.resolveWith(e)}).fail(function(){c.reject()})};
TaskTrackCore.prototype.initSettings=function(){Utils.log("Init App Settings");var c=this.db,e=this,e=this;$.ajaxSetup({url:"/server/sync.php",type:"POST",dataType:"JSON",async:!0,success:function(c,h,t){e.handleSuccess(c,h,t)},error:function(c,h,t){e.handleError(c,h,t)}});c.objectStore("settings").count().done(function(l){0===l?(c.objectStore("settings").add({login:null,password:null,up2date:!0},1),sWindow.wnd.show()):c.objectStore("settings").get(1).done(function(c){null===c.login||null===c.password?
sWindow.wnd.show():($("#settings-login").val(c.login),$("#settings-pass").val("").prop("placeholder","Type to change password or leave empty..."),e.checkLogin());e.up2date=c.up2date})})};TaskTrackCore.prototype.checkLogin=function(){this.syncServer2Client()};
TaskTrackCore.prototype.clearTableListCache=function(c,e){var l=this;void 0===e&&!0!==e&&(this.up2date=!1,this.changeSyncState());var h=this.getTableList(c[1]);h.done(function(e){switch(c){case TT_PROJECTS:l.projectList=e;break;case TT_TASKS:l.taskList=e}}).fail(function(){throw Error("Failed to get data from inDB!");});return h};
TaskTrackCore.prototype.getTableList=function(c){var e=$.Deferred(),l=this,h={count:0,list:[]};this.db.objectStore(c).index("status").count().done(function(t){if(0<t){h.count=t;var p=0;l.db.objectStore(c).index("status").each(function(c){h.list.push(c.value);p++},DB_ALL).done(function(){h.count=p;e.resolve(h)}).fail(function(c){e.reject(c)})}else e.resolve(h)});return e.promise()};
TaskTrackCore.prototype.getCurrDate=function(){var c=new Date,e=c.getFullYear(),l=10>c.getMonth()+1?"0"+(c.getMonth()+1):c.getMonth()+1,c=10>c.getDate()?"0"+c.getDate():c.getDate();return[e,l,c].join("-")};TaskTrackCore.prototype.normalizeTime=function(c,e){if("object"!=typeof c)throw Error("Invalid argument!");c.h=parseInt(c.h);c.m=parseInt(c.m);c.s=parseInt(c.s);c.h=10>c.h?"0"+c.h:c.h;c.m=10>c.m?"0"+c.m:c.m;c.s=10>c.s?"0"+c.s:c.s;return!0===e?[c.h,c.m,c.s].join(":"):c};
TaskTrackCore.prototype.changeSyncState=function(c){var e=this;c=!!c;this.db.objectStore("settings").get(1).done(function(l){l.up2date=c;e.db.objectStore("settings").put(l,1)})};TaskTrackCore.prototype.checkNetConn=function(){var c=$.Deferred(),e=!1;try{$.ajax({url:"/server/check_conn.php",type:"GET",async:!0,success:function(){e=!0;c.resolve(e)},error:function(){e=!1;c.resolve(e)}})}catch(l){}return c.promise()};
TaskTrackCore.prototype.getData2Sync=function(){var c=$.Deferred(),e={},l={},h=this.db.objectStore(TT_PROJECTS[1]).each(function(c){e[c.key]=c.value}),t=this.db.objectStore(TT_TASKS[1]).each(function(c){l[c.key]=c.value});$.when(h,t).done(function(){var h={projects:e,tasks:l},h=JSON.stringify(h);c.resolve(h)}).fail(c.reject);return c.promise()};
TaskTrackCore.prototype.syncServer2Client=function(c){var e=this,l=50,h=7;void 0===c&&!0!==c&&(this.sharedDfd=$.Deferred(),l=0,h=17);this.dfdFlag=0;c=this.db.objectStore("settings").get(1);var t=this.checkNetConn();$.when(c,t).done(function(c,t){c=c[0];t?e.up2date?(Utils.log("Starting synchronization S2C..."),$.ajax({data:{method:"s2c",login:c.login,password:c.password},beforeSend:function(){errorWindow.showBefore(99,l,h)}}),e.sharedDfd.done(function(c){var h=c.data.projects,l=c.data.tasks,p=[];e.dbAdapter.flushTaskAndProj().done(function(){for(var c in h)p.push(e.db.objectStore(TT_PROJECTS[1]).put(h[c]));
for(c in l)p.push(e.db.objectStore(TT_TASKS[1]).put(l[c]));$.when(p).done(function(){e.renderTaskAndProj()}).fail(function(){throw Error("Failed to save data to inDB!");});Utils.log("S2C Complete!")}).fail(function(){throw Error("Failed to update inDB!");})})):e.syncClient2Server(!0).done(function(){e.syncServer2Client(!0)}):errorWindow.show("Check your Internet connection!")});return this.sharedDfd.promise()};
TaskTrackCore.prototype.syncClient2Server=function(c){var e=this,l=99,h=17;void 0!==c&&!0===c&&(l=49,h=7);this.sharedDfd2=$.Deferred();this.dfdFlag=1;c=this.db.objectStore("settings").get(1);var t=this.checkNetConn();$.when(c,t).done(function(c,t){c=c[0];t?e.up2date?errorWindow.show("Synchronization Completed!",!1):(Utils.log("Starting synchronization C2S..."),e.getData2Sync().done(function(e){$.ajax({data:{method:"c2s",data:e,login:c.login,password:c.password},beforeSend:function(){errorWindow.showBefore(l,
0,h)}})}),e.sharedDfd2.done(function(){Utils.log("C2S Complete!");e.up2date=!0;e.changeSyncState(!0)})):errorWindow.show("Check your Internet connection!")});return this.sharedDfd2.promise()};TaskTrackCore.prototype.renderTaskAndProj=function(){this.clearTableListCache(TT_PROJECTS,!0);this.clearTableListCache(TT_TASKS,!0).done(TaskList.render)};
TaskTrackCore.prototype.handleSuccess=function(c,e,l){Utils.log("Success!",c,c.msg);200==c.status?0==this.dfdFlag?this.sharedDfd.resolve(c,c.status):this.sharedDfd2.resolve(c,c.status):0==this.dfdFlag?this.sharedDfd.reject(c.status,c.msg):this.sharedDfd2.reject(c.status,c.msg);switch(c.status){case 200:errorWindow.show("Synchronization Completed!",!1);break;case E_INV_SYNC_METHOD:errorWindow.show("Invalid synchronization method!");break;case E_MISS_DATA:errorWindow.show("Missing data for sync!");
break;case E_MISS_LOGIN_PASS:errorWindow.show("Missing Login and/or Password!");setTimeout("sWindow.wnd.show()",2E3);break;case E_INV_LOGIN_PASS:errorWindow.show("Invalid Login and/or Password!");setTimeout("sWindow.wnd.show()",2E3);break;case E_FAIL_SAVE_DATA:errorWindow.show("Failed to synchronization data!")}};
TaskTrackCore.prototype.handleError=function(c,e,l){this.sharedDfd.reject(c.status,e);switch(c.status){case 404:errorWindow.show("404 - Not Found");break;default:errorWindow.show("Unknown Error: "+c.status+", "+e+", "+l)}};function DB_Adapter(c){var e=this,l=$.Deferred();this.dbName=""!==c.name?c.name:"DataBase";this.db=$.indexedDB(this.dbName,{schema:{1:function(c){c=c.createObjectStore("projectList",{autoIncrement:!0,keyPath:"id"});c.createIndex("name");c.createIndex("status")},2:function(c){c=c.createObjectStore("taskList",{autoIncrement:!0,keyPath:"id"});c.createIndex("name");c.createIndex("projectId");c.createIndex("status")},3:function(c){c.createObjectStore("settings")}}});this.db.then(function(h){Utils.log("Connected to Indexed DB "+
c.name+"! Version: "+h.version);l.resolve(e)},function(){Utils.log("Cannot create Indexed DB "+c.name);l.reject();throw Error("Cannot create Indexed DB_Adapter!");},function(){Utils.log("Creating Indexed DB_Adapter...");l.notify()});return l.promise()}DB_Adapter.prototype.flushTaskAndProj=function(){var c=$.Deferred(),e=this.db.objectStore(TT_PROJECTS[1]).clear(),l=this.db.objectStore(TT_TASKS[1]).clear();$.when(e,l).done(c.resolve).fail(c.reject);return c.promise()};
var DB_DELETED=0,DB_NORMAL=1,DB_MODIFIED=2,DB_NEW=3,DB_ALL=[DB_NORMAL,DB_NEW];DB_Adapter.prototype.version="1.0.0";DB_Adapter.prototype.dbName="";DB_Adapter.prototype.dbReady=!1;DB_Adapter.prototype.db=null;(function(c,e){function l(c){var e=null;switch(c){case 0:case 1:case "readwrite":case "readonly":e=c;break;default:e=w.READ_WRITE||"readwrite"}return e}var h=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,t=window.IDBKeyRange||window.webkitIDBKeyRange,p=window.IDBCursor||window.webkitIDBCursor||{};p.PREV=p.PREV||"prev";p.NEXT=p.NEXT||"next";var w=window.IDBTransaction||window.webkitIDBTransaction;c.extend({indexedDB:function(e,p){if(p){"number"===typeof p&&(p={version:p});
var w=p.version;if(p.schema&&!w){var D=-1,s;for(s in p.schema)D=D>s?D:s;w=p.version||D}}var u={request:function(e,h){return c.Deferred(function(c){try{var l="function"===typeof e?e(h):e;l.onsuccess=function(e){c.resolveWith(l,[l.result,e])};l.onerror=function(e){c.rejectWith(l,[l.error,e])};"undefined"!==typeof l.onblocked&&null===l.onblocked&&(l.onblocked=function(e){var h;try{h=l.result}catch(p){h=null}c.notifyWith(l,[h,e])});"undefined"!==typeof l.onupgradeneeded&&null===l.onupgradeneeded&&(l.onupgradeneeded=
function(e){c.notifyWith(l,[l.result,e])})}catch(p){p.name="exception",c.rejectWith(l,["exception",p])}})},transaction:function(c){return{objectStore:function(e){try{return u.objectStore(c.objectStore(e))}catch(h){return c.readyState!==c.DONE&&c.abort(),u.objectStore(null)}},createObjectStore:function(e,h){try{return u.objectStore(c.db.createObjectStore(e,h))}catch(l){c.readyState!==c.DONE&&c.abort()}},deleteObjectStore:function(e){try{c.db.deleteObjectStore(e)}catch(h){c.readyState!==c.DONE&&c.abort()}},
abort:function(){c.abort()}}},objectStore:function(c){for(var e={},h="add put get delete clear count".split(" "),l=0;l<h.length;l++)e[h[l]]=function(e){return function(){return u.request(function(h){return c[e].apply(c,h)},arguments)}}(h[l]);e.each=function(e,h,l){return u.cursor(function(){return l?c.openCursor(u.range(h),l):c.openCursor(u.range(h))},e)};e.index=function(e){return u.index(function(){return c.index(e)})};e.createIndex=function(e,h,l){2===arguments.length&&"string"===typeof h&&(l=
arguments[1],h=null);l||(l=e);return u.index(function(){return c.createIndex(l,e,h)})};e.deleteIndex=function(e){return c.deleteIndex(e)};return e},range:function(e){return c.isArray(e)?1===e.length?t.only(e[0]):t.bound(e[0],e[1],"undefined"===typeof e[2]?!1:e[2],"undefined"===typeof e[3]?!1:e[3]):"undefined"===typeof e?null:e},cursor:function(e,h){return c.Deferred(function(c){try{var l="function"===typeof e?e():e;l.onsuccess=function(e){if(l.result){var p={"delete":function(){return u.request(function(){return l.result["delete"]()})},
update:function(c){return u.request(function(){return l.result.update(c)})},next:function(c){this.data=c},key:l.result.key,value:l.result.value};c.notifyWith(l,[p,e]);var q=h.apply(l,[p]);try{if(!1===q)c.resolveWith(l,[null,e]);else if("number"===typeof q)l.result.advance.apply(l.result,[q]);else if(p.data)l.result["continue"].apply(l.result,[p.data]);else l.result["continue"]()}catch(s){c.rejectWith(l,[l.result,s])}}else c.resolveWith(l,[null,e])};l.onerror=function(e){c.rejectWith(l,[l.result,e])}}catch(p){p.type=
"exception",c.rejectWith(l,[null,p])}})},index:function(c){try{var e="function"===typeof c?c():c}catch(h){e=null}return{each:function(c,h,l){return u.cursor(function(){return l?e.openCursor(u.range(h),l):e.openCursor(u.range(h))},c)},eachKey:function(c,h,l){return u.cursor(function(){return l?e.openKeyCursor(u.range(h),l):e.openKeyCursor(u.range(h))},c)},get:function(c){return"function"===typeof e.get?u.request(e.get(c)):e.openCursor(u.range(c))},count:function(){if("function"===typeof e.count)return u.request(e.count());
throw"Count not implemented for cursors";},getKey:function(c){return"function"===typeof e.getKey?u.request(e.getKey(c)):e.openKeyCursor(u.range(c))}}}},B=u.request(function(){return w?h.open(e,parseInt(w)):h.open(e)});B.then(function(c,e){c.onversionchange=function(){p&&p.onversionchange&&!1!==p.onversionchange()||c.close()}},function(c,e){},function(c,e){if(e&&"upgradeneeded"===e.type){if(p&&p.schema)for(var h=e.oldVersion+1;h<=e.newVersion;h++)"function"===typeof p.schema[h]&&p.schema[h].call(this,
u.transaction(this.transaction));p&&"function"===typeof p.upgrade&&p.upgrade.call(this,u.transaction(this.transaction))}});return c.extend(B,{cmp:function(c,e){return h.cmp(c,e)},deleteDatabase:function(){return c.Deferred(function(c){B.then(function(l,p){l.close();u.request(function(){return h.deleteDatabase(e)}).then(function(e,h){c.resolveWith(this,[e,h])},function(e,h){c.rejectWith(this,[e,h])},function(e,h){c.notifyWith(this,[e,h])})},function(e,h){c.rejectWith(this,[e,h])},function(e,h){c.notifyWith(this,
[e,h])})})},transaction:function(e,h){!c.isArray(e)&&(e=[e]);h=l(h);return c.Deferred(function(c){B.then(function(l,p){var q;try{q=l.transaction(e,h),q.onabort=q.onerror=function(e){c.rejectWith(q,[e])},q.oncomplete=function(e){c.resolveWith(q,[e])}}catch(s){s.type="exception";c.rejectWith(this,[s]);return}try{c.notifyWith(q,[u.transaction(q)])}catch(t){t.type="exception",c.rejectWith(this,[t])}},function(e,h){c.rejectWith(this,[h,e])},function(c,e){})})},objectStore:function(s,t){function w(v){return c.Deferred(function(c){function w(e,
h){try{h(e.objectStore(s)).then(function(e,h){c.resolveWith(this,[e,h])},function(e,h){c.rejectWith(this,[e,h])})}catch(l){l.name="exception",c.rejectWith(e,[l,l])}}C.transaction(s,l(t)).then(function(){},function(A,E){if(A.code!==A.NOT_FOUND_ERR||!0!==t&&"object"!==typeof t)c.rejectWith(this,[A,E]);else{var D=this.result;D.close();B=u.request(function(){return h.open(e,(parseInt(D.version,10)||1)+1)});B.then(function(e,h){e.onversionchange=function(){p&&p.onversionchange&&!1!==p.onversionchange()||
e.close()};C.transaction(s,l(t)).then(function(){},function(e,h){c.rejectWith(this,[e,h])},function(c,e){w(c,v)})},function(e,h){c.rejectWith(this,[e,h])},function(e,h){if("upgradeneeded"===h.type)try{e.createObjectStore(s,!0===t?{autoIncrement:!0}:t)}catch(l){c.rejectWith(this,[l,h])}})}},function(c){w(c,v)})})}function v(c,e){return w(function(h){return h[c].apply(h,e)})}function D(c,e,h){return w(function(l){l=l.index(e);return l[c].apply(l[c],h)})}for(var C=this,J={},E="add delete get put clear count each".split(" "),
A=0;A<E.length;A++)J[E[A]]=function(c){return function(){return v(c,arguments)}}(E[A]);J.index=function(c){return{each:function(e,h,l){return D("each",c,[e,h,l])},eachKey:function(e,h,l){return D("eachKey",c,[e,h,l])},get:function(e){return D("get",c,[e])},count:function(){return D("count",c,[])},getKey:function(e){return D("getKey",c,[e])}}};return J}})}});c.indexedDB.IDBCursor=p;c.indexedDB.IDBTransaction=w;c.idb=c.indexedDB})(jQuery);
