var DEF_WIDTH=400,DEF_HEIGHT=200,DEF_MODAL=!1,DEF_SHOW_SPEED=400,DEF_HIDE_SPEED=DEF_SHOW_SPEED/2;
function WindowTT(a){this.title=void 0!==a.title?a.title:"";this.html=void 0!==a.html?a.html:"";this.width=void 0!==a.width?parseInt(a.width):DEF_WIDTH;this.height=void 0!==a.height?parseInt(a.height):DEF_HEIGHT;this.max_height=void 0!==a.max_height?parseInt(a.max_height):0;this.modal=void 0!==a.modal?!0==a.modal:DEF_MODAL;this.showSpeed=void 0!==a.showSpeed?parseInt(a.showSpeed):DEF_SHOW_SPEED;this.hideSpeed=void 0!==a.hideSpeed?parseInt(a.hideSpeed):DEF_HIDE_SPEED;this.closeAble=void 0!==a.closeAble?
!!a.closeAble:!0;this.bodyCtx=document.body;this.windowId=Utils.getId();this.init();this.windowState=1;return this}WindowTT.prototype.title="";WindowTT.prototype.html="";WindowTT.prototype.width=0;WindowTT.prototype.height=0;WindowTT.prototype.max_height=0;WindowTT.prototype.modal=DEF_MODAL;WindowTT.prototype.bodyCtx={};WindowTT.prototype.windowCtx={};WindowTT.prototype.modalCtx={};WindowTT.prototype.windowTitle={};WindowTT.prototype.windowCloseBtn={};WindowTT.prototype.windowHtml={};
WindowTT.prototype.windowId=0;WindowTT.prototype.closeAble=!0;WindowTT.prototype.windowState=0;
WindowTT.prototype.init=function(){if(0==this.windowState){if(this.modal){var a=document.createElement("div");a.setAttribute("id","win-modal-"+this.windowId);a.setAttribute("class","window-modal");a.setAttribute("style","opacity:0;display:none;");this.bodyCtx.appendChild(a);this.modalCtx=$("#win-modal-"+this.windowId)}var b=this.modal?" modal":"",a=document.createElement("div"),c="left:calc((100%/2) - "+this.width/2+"px)",d="top:calc((100%/2) - "+(0!=this.max_height?this.max_height:this.height)/2+
"px)";a.setAttribute("id","window-"+this.windowId);a.setAttribute("class","window-window"+b);b=0!=this.max_height?"max-height:"+this.max_height+"px;min-height:"+this.height+"px":"height:"+this.height+"px";a.setAttribute("style","opacity:0;display:none;width:"+this.width+"px;"+b+";"+d+";"+c);this.bodyCtx.appendChild(a);this.windowCtx=$("#window-"+this.windowId);a=document.createElement("div");a.setAttribute("class","window-title");a.innerHTML=this.title;var e=this;this.closeAble&&(c=document.createElement("span"),
c.setAttribute("class","window-close"),c.addEventListener("click",function(a){e.close()}),this.windowCloseBtn=c,a.appendChild(c));this.windowCtx.append(a);this.windowTitle=$("#window-"+this.windowId+" .window-title");a=document.createElement("div");a.setAttribute("class","window-html");b=0!=this.max_height?"max-height:"+(this.max_height-32):"height:"+(this.height-32);a.setAttribute("style",b+"px;overflow:auto;overflow-x:hidden;");a.innerHTML=this.html;this.windowHtml=a;this.windowCtx.append(a);this.windowHTML=
$("#window-"+this.windowId+" .window-html")}};WindowTT.prototype.setTitle=function(a){this.title=void 0!==a?a:"";this.windowTitle.html(this.title);this.closeAble&&this.windowTitle.append(this.windowCloseBtn)};WindowTT.prototype.getTitle=function(){return this.title};WindowTT.prototype.setHtml=function(a){this.html=void 0!==a?a:"";this.windowHtml.innerHTML=this.html};WindowTT.prototype.getHtml=function(){return this.html};WindowTT.prototype.setModal=function(a){this.modal=void 0!==a?!0==a:DEF_MODAL};
WindowTT.prototype.getModal=function(){return this.modal};WindowTT.prototype.show=function(){Utils.log("Window show");1===this.windowState&&(this.modal&&this.modalCtx.stop().animate({opacity:0.5},this.showSpeed).css("display",""),this.windowCtx.stop().animate({opacity:1},this.showSpeed).css("display",""));this.windowState=2;return this};
WindowTT.prototype.close=function(){Utils.log("Window close");if(2===this.windowState){if(this.modal){var a=this.modalCtx;this.modalCtx.stop().animate({opacity:0},this.hideSpeed,function(){a.css("display","none")})}var b=this.windowCtx;this.windowCtx.stop().animate({opacity:0},this.hideSpeed,function(){b.css("display","none")})}this.windowState=1;return this};WindowTT.prototype.toggle=function(){1===this.windowState?this.show():2===this.windowState&&this.close();return this};
